Repository planetarium/web9c, pull requests merged in 2023-06, with the labels that each got.

#12 Correct base path
  src/Routes.tsx
Labels: bug, Extra Small

#13 Correct wrong string slice
  src/graphql.ts
Labels: bug, Extra Small

#14 Reload lobby data per 2 seconds
  src/graphql.ts
  src/hooks/useInterval.ts
  src/views/LobbyView/index.tsx
Labels: bug, Extra Small

#15 Use web3 secret storage
  .yarn/patches/@planetarium-account-web3-secret-storage-npm-1.4.0-dev.2023658319-7067e972f4.patch
  package.json
  src/hooks/useAccountMetadatas.ts
  src/views/ImportView/index.tsx
  src/views/LoginView/index.tsx
  src/views/RegisterView/index.tsx
  src/views/WelcomeView/index.tsx
  yarn.lock
Labels: Large

#17 Show avatar view with inventory
  package.json
  src/Routes.tsx
  src/graphql.ts
  src/views/AvatarView/index.tsx
  src/views/LobbyView/Avatar.tsx
  src/views/LobbyView/index.tsx
  yarn.lock
Labels: Large

#21 Refactor
  src/api/getAvatarInventory.ts
  src/api/getAvatarStates.ts
  src/api/getGoldBalance.ts
  src/api/getNextTxNonce.ts
  src/api/getRawState.ts
  src/api/graphqlClient.ts
  src/api/index.ts
  src/api/shortcuts.ts
  src/api/stageTransaction.ts
  src/constants.ts
  src/graphql.ts
  src/views/AvatarView/Inventory/index.tsx
  src/views/AvatarView/Inventory/tabs/ConsumableTab.tsx
  src/views/AvatarView/Inventory/tabs/CostumeTab.tsx
  src/views/AvatarView/Inventory/tabs/EquipmentTab.tsx
  src/views/AvatarView/Inventory/tabs/MaterialTab.tsx
  src/views/AvatarView/index.tsx
  src/views/LobbyView/Avatar.tsx
  src/views/LobbyView/index.tsx
  src/views/LobbyView/tabs/StakeTab.tsx
  src/views/LobbyView/tabs/TransferTab.tsx
  src/web3-account.ts
Labels: Extra Large

#22 Battle with selected equipment
  package.json
  src/api/getRawState.ts
  src/api/shortcuts.ts
  src/api/stageTransaction.ts
  src/constants.ts
  src/views/AvatarView/Inventory/tabs/CostumeTab.tsx
  src/views/AvatarView/index.tsx
  src/views/AvatarView/tabs/BattleTab/index.tsx
  src/views/AvatarView/tabs/InventoryTab/index.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/ConsumableTab.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/CostumeTab.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/EquipmentTab.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/ItemIcon.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/MaterialTab.tsx
  src/views/LobbyView/tabs/StakeTab.tsx
  src/views/LobbyView/tabs/TransferTab.tsx
  yarn.lock
Labels: Large

#23 Refactor
  src/App.tsx
  src/api/getAvatarInventory.ts
  src/api/getAvatarStates.ts
  src/api/getGoldBalance.ts
  src/api/getNextTxNonce.ts
  src/api/index.ts
  src/api/shortcuts.ts
  src/api/useAvatarStates.ts
  src/api/useGoldBalance.ts
  src/api/useNextTxNonce.ts
  src/contexts/Account.tsx
  src/views/AvatarView/tabs/BattleTab/index.tsx
  src/views/AvatarView/tabs/InventoryTab/tabs/EquipmentTab.tsx
  src/views/LobbyView/index.tsx
  src/views/LobbyView/tabs/StakeTab.tsx
  src/views/LobbyView/tabs/TransferTab.tsx
  src/views/LoginView/index.tsx
Labels: Extra Large

#24 Add rewrite rule for SPA
  netlify.toml
Labels: bug

#27 Show txresult
  src/components/ui/NcscanTransactionLink.tsx
  src/hooks/useTransactionResult.ts
  src/views/AvatarView/tabs/BattleTab/TransactionResult.tsx
  src/views/AvatarView/tabs/BattleTab/index.tsx
  src/views/LobbyView/index.tsx
Labels: Small

#28 Refactor
  src/Routes.tsx
  src/api/getRawState.ts
  src/api/index.ts
  src/hooks/index.ts
  src/hooks/useAccountContext.ts
  src/hooks/useAccountMetadatas.ts
  src/hooks/useAvatarInventory.ts
  src/hooks/useAvatarStates.ts
  src/hooks/useGoldBalance.ts
  src/hooks/useNextTxNonce.ts
  src/hooks/useRawState.ts
  src/hooks/useTransactionResult.ts
  src/views/AvatarView/index.tsx
  src/views/AvatarView/tabs/BattleTab/TransactionResult.tsx
  src/views/AvatarView/tabs/BattleTab/index.tsx
  src/views/AvatarView/tabs/InventoryTab/index.tsx
  src/views/ImportView/index.tsx
  src/views/LobbyView/index.tsx
  src/views/LoginView/index.tsx
  src/views/WelcomeView/index.tsx
Labels: Large

#29 Navigate user
  src/views/AvatarView/index.tsx
  src/views/LobbyView/index.tsx
Labels: Extra Small

#31 Introduce HOWTOPLAY.md
  HOWTOPLAY.md
  src/views/AvatarView/tabs/BattleTab/index.tsx
Labels: documentation, Small

#37 Show address after login
  .eslintrc
  .eslintrc.cjs
  .github/workflows/build.yaml
  .gitignore
  .prettierignore
  lefthook.yml
  netlify.toml
  package.json
  postcss.config.js
  src/api/index.ts
  src/api/shortcuts.ts
  src/api/stageTransaction.ts
  src/components/EndpointSelect.tsx
  src/components/Spinner.tsx
  src/graphql/fragment-masking.ts
  src/graphql/gql.ts
  src/graphql/graphql.ts
  src/graphql/index.ts
  src/hooks/index.ts
  src/hooks/useAccountContext.ts
  src/pages/index.page.tsx
  src/pages/main.page.tsx
  src/renderer/Layout.tsx
  src/renderer/Link.tsx
  src/renderer/_default.page.client.tsx
  src/renderer/_error.page.tsx
  src/renderer/getPageTitle.ts
  src/renderer/types.ts
  src/renderer/usePageContext.tsx
  src/sections/Address.tsx
  src/sections/Endpoint.tsx
  src/sections/EndpointInfo.tsx
  src/sections/PublicKey.tsx
  src/sections/SendSection.tsx
  src/store/account.ts
  src/store/endpoint.ts
  src/utils/Uint8Array.ts
  src/vite-env.d.ts
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: Extra Large

#44 Section framing
  .eslintrc
  public/sections/Address.tsx
  public/sections/EndpointInfo.tsx
  public/sections/EndpointSelect.tsx
  public/sections/PublicKey.tsx
  public/sections/SendSection.tsx
  src/components/ActionForm.tsx
  src/components/AvatarSelector.tsx
  src/components/EndpointInfo.tsx
  src/components/EndpointList.tsx
  src/components/KeyManage.tsx
  src/components/TransactionForm.tsx
  src/components/TransactionResultList.tsx
  src/components/ui/Section.tsx
  src/components/ui/Slot.tsx
  src/components/ui/Spinner.tsx
  src/components/ui/Title.tsx
  src/pages/index.page.tsx
  src/pages/main.page.tsx
  src/renderer/Layout.tsx
  src/sections/Account.tsx
  src/sections/Endpoint.tsx
  src/sections/Transaction.tsx
Labels: enhancement

#39 Setup docs
  docs/.gitignore
  docs/README.md
  docs/book.toml
  docs/netlify.toml
  docs/src/GET_STRATED.md
  docs/src/OVERVIEW.md
  docs/src/SUMMARY.md
  docs/src/concepts/README.md
  docs/src/concepts/reflecting-behavior-on-the-blockchain.md
  docs/src/internals/README.md
  docs/src/internals/security.md
  docs/src/qna/README.md
  docs/src/qna/lib9c-wasm-actions-dont-work.md
Labels: documentation, Small
